@startuml

title Strategy Pattern

abstract class Context
{
    + void ContextMethod()
    + void SetterMethod(Strategy strategy)
}

Context <|-- Class1
Context <|-- Class2

interface Strategy
{
    + void StrategyMethod()
}

class ConcreteStrategy1
{
    + StrategyMethod()
}

class ConcreteStrategy2
{
    + StrategyMethod()
}

Context o-right- Strategy

Strategy <|.. ConcreteStrategy1
Strategy <|.. ConcreteStrategy2

@enduml